import { test, expect, settle, crashesOnly, ApiClient } from '../../fixtures';
import { acceptNativeDialogs } from '../../pages';
import {
  BankConfigPage,
  BankMasterPage,
  BankMigratePage,
  BankToasts,
  BranchCountriesPage,
  selectBranch,
} from '../../pages/banks';

/**
 * Where an employee's salary is sent, and who is allowed to decide it.
 *
 * This is the one screen in the product that writes a payment destination
 * directly — no approval chain, no second signature. `POST /bank-change-requests`
 * is the employee's route and it can be governed by a workflow; the migration
 * path is HR verifying a legacy free-text record by hand and writing an ACTIVE
 * `EmployeeBankDetail` in a single click. If that click accepts a wrong number,
 * the money goes somewhere else and nothing in the system objects.
 *
 * So the assertion this file is built around is not "the button worked". It is
 * that a bad IBAN is REFUSED and the reason reaches the person typing it. The
 * backend suite (`finance-bank-migration.e2e-spec.ts`, 44 cases) already proves
 * the server refuses; what is untested until here is whether the refusal
 * survives the trip to the screen, because this page renders the structured
 * `errors` map rather than the flat `message` and a shape change there degrades
 * a precise sentence into "Failed to migrate".
 *
 * ## Four screens, one rule
 *
 * The chain is real and the specs follow it: branch banking countries decide
 * which countries an employee may bank in → the field config decides which
 * fields those countries demand → the bank master decides which banks exist
 * inside them → migration is where all three land on one person. Each describe
 * changes one link and asserts the change appears downstream, because that
 * coupling is invisible on any single screen.
 *
 * ## Facts this file encodes
 *
 *   • A candidate is an ACTIVE employee with a legacy `profile.bankName` and NO
 *     active bank detail. Migrating one removes it from that set permanently —
 *     there is no API that deactivates a detail — so the journey hires its own
 *     candidate rather than consuming the seeded one, and terminates it
 *     afterwards. Using EMP002 would make this file work exactly once per
 *     database.
 *   • The country picker on a migration card is rendered ONLY where the branch
 *     allows more than one banking country. With exactly one it is pre-selected
 *     and absent, which is why the branch-countries describe below turns HO
 *     from one country into two and watches the picker appear.
 *   • The `Autofill (dev)` button is gated on
 *     `process.env.NODE_ENV !== 'production'` and this suite runs a PRODUCTION
 *     build (`e2e/start-frontend.sh` → `next build`), so it is dead-code
 *     eliminated. Every IBAN here is generated by `omIban()` below, whose
 *     algorithm is copied from the backend spec's generator. A hand-written
 *     IBAN fails for the wrong reason and makes the test lie.
 */

test.describe.configure({ mode: 'serial' });

const isProject = (name: string) => test.info().project.name === name;

/** Distinct per run and visible on screen, so leftovers are identifiable. */
const marker = `pw-bank-${Date.now().toString(36)}`;

/** The country the baseline configures a field schema and banks for. */
const COUNTRY = 'OM';
/** A second, deliberately different country, used only to widen a branch. */
const OTHER_COUNTRY = 'AE';

const OM_IBAN_LENGTH = 23;

/**
 * A structurally valid Omani IBAN carrying `bankCode`.
 *
 * Copied from `apps/backend/test/finance-bank-migration.e2e-spec.ts`, which
 * documents why it is generated rather than hardcoded: the server checks the
 * ISO 7064 mod-97 checksum over the rearranged string AND cross-checks the
 * 3-digit CBO bank code at positions 5-7, so an invented IBAN is refused for a
 * reason that has nothing to do with the case under test.
 *
 * 23 characters = "OM" + 2 check digits + 19 BBAN, bank code first.
 */
function omIban(bankCode: string, account = '0000012991234'): string {
  const bban = `${bankCode.padStart(3, '0')}${account}`
    .padEnd(OM_IBAN_LENGTH - 4, '0')
    .slice(0, OM_IBAN_LENGTH - 4);
  const numeric = `${bban}OM00`
    .split('')
    .map((c) => (/[A-Z]/.test(c) ? String(c.charCodeAt(0) - 55) : c))
    .join('');
  let remainder = 0;
  for (const digit of numeric) remainder = (remainder * 10 + Number(digit)) % 97;
  return `OM${String(98 - remainder).padStart(2, '0')}${bban}`;
}

/** The same IBAN with its last digit changed — one mistyped character, nothing else. */
function mistype(iban: string): string {
  const last = iban.slice(-1);
  return iban.slice(0, -1) + (last === '0' ? '1' : '0');
}

interface BankRecord {
  id: string;
  country: string;
  name: string;
  bankCode: string | null;
  isActive: boolean;
}

interface Candidate {
  id: string;
  fullName: string;
  employeeCode: string;
  countries: string[];
}

interface CurrentDetail {
  detail: { bankId: string; values: Record<string, string> } | null;
  countries: string[];
}

interface BranchRow {
  id: string;
  code: string;
  bankingCountries: string[];
}

const rows = <T>(value: T[] | { data?: T[] } | null | undefined): T[] =>
  Array.isArray(value) ? value : (value?.data ?? []);

/**
 * Hires a throwaway employee carrying a legacy free-text bank record.
 *
 * Two steps because they are two models: `POST /employees` creates the person,
 * and the legacy fields live on `EmployeeProfile`, which only
 * `PATCH /employees/:id/profile` writes. Without the second call the person is
 * not a migration candidate at all — `profile.bankName: { not: null }` is half
 * of what defines one.
 */
async function hireCandidate(api: ApiClient, branchId: string, tag: string): Promise<Candidate> {
  type Department = { id: string; code: string };
  const departments = rows(await api.get<Department[]>('/departments'));
  const ops = departments.find((d) => d.code === 'E2E-OPS') ?? departments[0];
  if (!ops) throw new Error('Baseline seed missing a department to hire into');

  const created = await api.post<Candidate>('/employees', {
    fullName: `E2E Bank ${tag}`,
    dateOfBirth: '1993-04-11',
    email: `e2e.bank.${tag.toLowerCase()}@company.com`,
    autoGenerateIdCard: true,
    branchId,
    departmentId: ops.id,
    position: 'Engineer',
    startDate: '2025-01-06',
    baseSalary: 40000,
  });

  await api.patch(`/employees/${created.id}/profile`, {
    bankName: 'Legacy Bank plc',
    bankBranch: 'Legacy Branch',
    bankAccountNumber: '11223344',
    bankAccountHolderName: `E2E Bank ${tag}`,
  });

  return { ...created, countries: [] };
}

test.describe('a legacy bank record is verified and migrated', () => {
  // Role gate, in a hook rather than in each body: a skip decided here
  // happens before the page fixture is built, so no browser opens.
  test.beforeEach(() => {
    test.skip(!isProject('admin'), 'migration is an HR/admin flow');
  });

  let adminApi: ApiClient;
  let branchId = '';
  let candidateId = '';
  let bank: BankRecord | null = null;
  let otherBankCode = '';
  let setupError = '';

  test.beforeAll(async () => {
    if (!isProject('admin')) return;
    adminApi = await ApiClient.as('admin');

    try {
      branchId = await adminApi.firstBranchId();
      adminApi.withBranch(branchId);

      const banks = rows(await adminApi.get<BankRecord[]>(`/banks?country=${COUNTRY}&activeOnly=true`));
      // A bank WITH a code, because the code is what the IBAN has to carry —
      // one without would make the cross-check unreachable and the case vacuous.
      bank = banks.find((b) => !!b.bankCode) ?? null;
      otherBankCode = banks.find((b) => b.bankCode && b.bankCode !== bank?.bankCode)?.bankCode ?? '046';

      const hired = await hireCandidate(adminApi, branchId, marker.slice(-6).toUpperCase());
      candidateId = hired.id;
    } catch (e) {
      setupError = (e as Error).message;
    }
  });

  test.afterAll(async () => {
    if (isProject('admin') && candidateId) {
      // Terminated, not deleted: the soft delete is the only exit the API
      // offers, and a TERMINATED employee drops out of the candidate query
      // (`status: 'ACTIVE'`), which is what stops these accumulating.
      await adminApi
        .delete(`/employees/${candidateId}?clearanceOverrideReason=${encodeURIComponent(marker)}`)
        .catch(() => undefined);
    }
    await adminApi?.dispose();
  });

  test('the candidate is listed with their legacy record and their branch countries', async ({
    page,
    problems,
  }) => {
    expect(candidateId, `no candidate to migrate: ${setupError}`).toBeTruthy();
    expect(bank, `no OM bank with a bank code is configured: ${setupError}`).toBeTruthy();

    await selectBranch(page, branchId);
    const migrate = new BankMigratePage(page);
    await migrate.open();

    expect(await migrate.hasRow(candidateId), 'the newly hired candidate is not on the screen').toBe(true);
    expect(await migrate.isEmpty(), 'the empty state showed while a candidate exists').toBe(false);

    // The branch's allowed banking countries, projected onto the card. This is
    // the link every downstream control hangs off.
    expect(await migrate.countries(candidateId)).toEqual([COUNTRY]);

    settle(problems, 'the migration candidate list');
  });

  test('one allowed country pre-selects itself, offers no picker, and narrows the bank list', async ({
    page,
    problems,
  }) => {
    test.skip(!candidateId, 'no candidate was hired');

    await selectBranch(page, branchId);
    const migrate = new BankMigratePage(page);
    await migrate.open();

    // With exactly one country there is nothing to choose, so the screen does
    // not ask. A picker here would be a question with one answer.
    expect(
      await migrate.hasCountryPicker(candidateId),
      'a country picker was offered for a branch with one banking country',
    ).toBe(false);

    const banks = await migrate.bankOptions(candidateId);
    expect(banks.length, 'the bank picker offered nothing for OM').toBeGreaterThan(0);

    // Every option must be an OM bank. Read back from the server rather than
    // from the labels — the label is a bank name, and names are not selectors.
    const all = rows(await adminApi.get<BankRecord[]>('/banks?activeOnly=true'));
    for (const option of banks) {
      const record = all.find((b) => b.id === option.value);
      expect(record, `the picker offered a bank the server does not list: ${option.value}`).toBeTruthy();
      expect(record!.country).toBe(COUNTRY);
    }

    settle(problems, 'the migration bank picker');
  });

  test('the dynamic fields are the country schema, and Migrate is dead until a bank is chosen', async ({
    page,
    problems,
  }) => {
    test.skip(!candidateId, 'no candidate was hired');

    await selectBranch(page, branchId);
    const migrate = new BankMigratePage(page);
    await migrate.open();

    // The form is configuration, not code: whatever `CountryBankingField` holds
    // for OM is what renders. Asserted against the server's own answer so a
    // client that quietly drops a field is caught.
    const schema = rows(
      await adminApi.get<Array<{ fieldKey: string }>>(`/banking-config/fields?country=${COUNTRY}`),
    );
    expect(schema.length, 'no banking fields are configured for OM').toBeGreaterThan(0);
    expect((await migrate.fieldKeys(candidateId)).sort()).toEqual(
      schema.map((f) => f.fieldKey).sort(),
    );

    // No bank chosen yet — the destination is the one thing that cannot be
    // inferred, so the screen refuses to submit without it.
    expect(
      await migrate.canSubmit(candidateId),
      'Migrate was live before a bank had been chosen',
    ).toBe(false);

    await migrate.selectBank(candidateId, bank!.id);
    expect(await migrate.canSubmit(candidateId), 'Migrate stayed dead after a bank was chosen').toBe(true);

    settle(problems, 'the migration form');
  });

  test('a single mistyped digit is refused, and the checksum sentence reaches the screen', async ({
    page,
    problems,
  }) => {
    test.skip(!candidateId, 'no candidate was hired');

    // The refusal is a 400, which the browser logs on its way to the toast.
    // That console line is the system working, so only crashes are fatal here.
    crashesOnly(problems);

    await selectBranch(page, branchId);
    const migrate = new BankMigratePage(page);
    const toasts = new BankToasts(page);
    await migrate.open();

    await migrate.selectBank(candidateId, bank!.id);
    await migrate.fill(candidateId, {
      accountHolderName: `E2E Bank ${marker}`,
      iban: mistype(omIban(bank!.bankCode!)),
    });
    await migrate.submit(candidateId);

    // The claim: the server's per-field `errors` map survives the trip. This
    // page renders `Object.values(errors)`, not `message` — a shape change
    // there degrades a precise sentence into "Failed to migrate", which is the
    // exact production incident recorded in docs/LOAN-ADVANCES-TEST-CASES.md.
    const text = await toasts.waitFor('error');
    expect(text, 'the refusal did not name the checksum').toMatch(/check digit/i);

    // The card stays: a refused migration must not look like a completed one.
    expect(await migrate.hasRow(candidateId), 'the candidate vanished after a REFUSED migration').toBe(true);

    // And nothing was written. A screen that says no while the server said yes
    // is the worse half of this failure mode.
    const current = await adminApi.get<CurrentDetail>(
      `/bank-change-requests/employee/${candidateId}/current`,
    );
    expect(current.detail, 'a bank detail was written despite the refusal').toBeFalsy();

    settle(problems, 'a refused migration');
  });

  test('an IBAN that routes to a different bank is refused, naming the bank code', async ({
    page,
    problems,
  }) => {
    test.skip(!candidateId, 'no candidate was hired');

    crashesOnly(problems);

    await selectBranch(page, branchId);
    const migrate = new BankMigratePage(page);
    const toasts = new BankToasts(page);
    await migrate.open();

    await migrate.selectBank(candidateId, bank!.id);
    // Structurally perfect, checksum correct, routed to somebody else. Only the
    // embedded-bank-code cross-check catches this one, and it is the failure
    // that actually moves money to the wrong institution.
    await migrate.fill(candidateId, {
      accountHolderName: `E2E Bank ${marker}`,
      iban: omIban(otherBankCode),
    });
    await migrate.submit(candidateId);

    const text = await toasts.waitFor('error');
    expect(text, 'the refusal did not name the bank code').toMatch(/bank code/i);
    expect(await migrate.hasRow(candidateId)).toBe(true);

    const current = await adminApi.get<CurrentDetail>(
      `/bank-change-requests/employee/${candidateId}/current`,
    );
    expect(current.detail, 'a mis-routed IBAN was stored').toBeFalsy();

    settle(problems, 'a mis-routed IBAN');
  });

  test('a valid IBAN migrates: the card goes and one ACTIVE detail exists', async ({
    page,
    problems,
  }) => {
    test.skip(!candidateId, 'no candidate was hired');

    await selectBranch(page, branchId);
    const migrate = new BankMigratePage(page);
    await migrate.open();

    await migrate.selectBank(candidateId, bank!.id);
    await migrate.fill(candidateId, {
      accountHolderName: `E2E Bank ${marker}`,
      iban: omIban(bank!.bankCode!),
    });
    await migrate.submit(candidateId);

    // The screen's own success signal: the card is removed from the list.
    await migrate.expectMigrated(candidateId);

    // And the server's, which is the one that matters. Values come back masked
    // — the detail is sensitive by configuration — so the assertion is on the
    // bank it was routed to, not on the account.
    await expect
      .poll(
        async () => {
          const current = await adminApi.get<CurrentDetail>(
            `/bank-change-requests/employee/${candidateId}/current`,
          );
          return current.detail?.bankId ?? null;
        },
        { timeout: 20_000 },
      )
      .toBe(bank!.id);

    settle(problems, 'a completed migration');
  });

  test('a migrated employee cannot be overwritten from this screen', async ({ page, problems }) => {
    test.skip(!candidateId, 'no candidate was hired');

    await selectBranch(page, branchId);
    const migrate = new BankMigratePage(page);
    await migrate.open();

    // Not cosmetic tidying. The migration endpoint's payroll lock carries a
    // deliberate carve-out — `exemptFirstTime` — so a FIRST-TIME write is
    // allowed while a run is open, and only an OVERWRITE is refused with
    // "Bank details are locked while a payroll run is in progress"
    // (BNK-API-29/30). The screen's half of that rule is this: it lists only
    // employees with no active detail, so from here an overwrite is not
    // reachable at all. If a migrated employee ever reappeared on this list,
    // the carve-out would become a way to redirect a live salary mid-run.
    expect(
      await migrate.hasRow(candidateId),
      'a migrated employee is still offered for migration — the overwrite path is open',
    ).toBe(false);

    // The other side of the same rule, asserted where it is enforced: the
    // employee's stored detail is the one the migration wrote, and the API is
    // the only route to a second write.
    const current = await adminApi.get<CurrentDetail>(
      `/bank-change-requests/employee/${candidateId}/current`,
    );
    expect(current.detail?.bankId).toBe(bank!.id);

    settle(problems, 'the candidate list after a migration');
  });

  test('Autofill is a dev-only affordance and is absent from the build under test', async ({
    page,
    problems,
  }) => {
    await selectBranch(page, branchId);
    const migrate = new BankMigratePage(page);
    await migrate.open();

    const ids = await migrate.employeeIds();
    test.skip(ids.length === 0, 'no candidates remain to inspect');

    // `isDevMode()` reads `process.env.NODE_ENV`, which Next replaces at BUILD
    // time — so a production bundle folds the check to `false` and eliminates
    // every caller. This suite builds with `next build`, so the button must not
    // be here. The assertion is the guard on that promise: a refactor to a
    // runtime flag would ship a "fill in a valid IBAN for me" button to real HR
    // users, and nothing else in the suite would notice.
    expect(
      await migrate.hasAutofill(ids[0]),
      'the dev-only Autofill button survived a production build',
    ).toBe(false);

    settle(problems, 'the migration screen in a production build');
  });
});

/**
 * The link above migration: which countries a branch may bank in.
 *
 * Worth its own journey because the coupling is invisible from either screen.
 * Branch Countries shows a chip list and says nothing about migration; the
 * migration card shows a picker, or doesn't, and says nothing about why. The
 * only place the rule is observable is across the two.
 */
test.describe('branch banking countries drive the migration country list', () => {
  // Role gate, in a hook rather than in each body: a skip decided here
  // happens before the page fixture is built, so no browser opens.
  test.beforeEach(() => {
    test.skip(!isProject('admin'), 'branch countries are an HR/admin flow');
  });

  test.describe.configure({ mode: 'serial' });

  let adminApi: ApiClient;
  let branchId = '';
  let candidateId = '';
  let original: string[] = [];
  let setupError = '';

  test.beforeAll(async () => {
    if (!isProject('admin')) return;
    adminApi = await ApiClient.as('admin');

    try {
      branchId = await adminApi.firstBranchId();
      adminApi.withBranch(branchId);

      const branches = rows(await adminApi.get<BranchRow[]>('/banks/branch-countries'));
      original = branches.find((b) => b.id === branchId)?.bankingCountries ?? [];

      const hired = await hireCandidate(adminApi, branchId, `${marker.slice(-5).toUpperCase()}C`);
      candidateId = hired.id;
    } catch (e) {
      setupError = (e as Error).message;
    }
  });

  test.afterAll(async () => {
    if (isProject('admin')) {
      // Restored over the API rather than through the screen: this value gates
      // the migration screen for the WHOLE suite, and a UI failure mid-test
      // must not leave HO banking in two countries for everything that runs
      // after.
      if (branchId) {
        await adminApi
          .put(`/banks/branch-countries/${branchId}`, { countries: original })
          .catch(() => undefined);
      }
      if (candidateId) {
        await adminApi
          .delete(`/employees/${candidateId}?clearanceOverrideReason=${encodeURIComponent(marker)}`)
          .catch(() => undefined);
      }
    }
    await adminApi?.dispose();
  });

  test('adding a second banking country makes the migration card ask which one', async ({
    page,
    problems,
  }) => {
    expect(candidateId, `no candidate to observe: ${setupError}`).toBeTruthy();
    expect(original, 'HO has no banking countries configured').toContain(COUNTRY);

    await selectBranch(page, branchId);
    const countries = new BranchCountriesPage(page);
    await countries.open();

    expect(await countries.countries(branchId)).toEqual(original);
    // Save is dead until the draft differs — a screen that let you save an
    // unchanged list would report success for having done nothing.
    expect(await countries.canSave(branchId), 'Save was live on an untouched branch').toBe(false);

    await countries.addCountry(branchId, OTHER_COUNTRY);
    expect(await countries.isDirty(branchId), 'adding a chip did not mark the branch dirty').toBe(true);
    await countries.save(branchId);

    // Re-read from the server: the chip list is local draft state until saved,
    // so asserting on it alone would pass whether or not the PUT happened.
    await expect
      .poll(
        async () => {
          const branches = rows(await adminApi.get<BranchRow[]>('/banks/branch-countries'));
          return branches.find((b) => b.id === branchId)?.bankingCountries ?? [];
        },
        { timeout: 15_000 },
      )
      .toContain(OTHER_COUNTRY);

    // The downstream effect, which is the point of the case.
    const migrate = new BankMigratePage(page);
    await migrate.open();
    // Compared as a set: the endpoint normalises and de-duplicates the list, and
    // this case is about WHICH countries reach the card, not their order.
    expect([...(await migrate.countries(candidateId))].sort()).toEqual(
      [COUNTRY, OTHER_COUNTRY].sort(),
    );
    expect(
      await migrate.hasCountryPicker(candidateId),
      'two allowed countries produced no picker — the second one is unreachable',
    ).toBe(true);

    settle(problems, 'widening a branch to two banking countries');
  });

  test('removing it again collapses the card back to one pre-selected country', async ({
    page,
    problems,
  }) => {
    test.skip(!candidateId, 'no candidate was hired');

    await selectBranch(page, branchId);
    const countries = new BranchCountriesPage(page);
    await countries.open();

    await countries.removeCountry(branchId, OTHER_COUNTRY);
    await countries.save(branchId);

    await expect
      .poll(
        async () => {
          const branches = rows(await adminApi.get<BranchRow[]>('/banks/branch-countries'));
          return branches.find((b) => b.id === branchId)?.bankingCountries ?? [];
        },
        { timeout: 15_000 },
      )
      .not.toContain(OTHER_COUNTRY);

    const migrate = new BankMigratePage(page);
    await migrate.open();
    expect(await migrate.countries(candidateId)).toEqual([COUNTRY]);
    expect(await migrate.hasCountryPicker(candidateId)).toBe(false);

    settle(problems, 'narrowing a branch back to one banking country');
  });
});

/**
 * The bank master — the reference data every picker above reads.
 *
 * ADMIN alone may write it (`BNK-API-03`), and there is no delete: a bank is
 * retired by deactivation, which is why the last case here doubles as this
 * describe's cleanup.
 */
test.describe('the bank master is ADMIN territory', () => {
  // Role gate, in a hook rather than in each body: a skip decided here
  // happens before the page fixture is built, so no browser opens.
  test.beforeEach(() => {
    test.skip(!isProject('admin'), 'the bank master is admin-only');
  });

  test.describe.configure({ mode: 'serial' });

  let adminApi: ApiClient;
  let branchId = '';
  let createdBankId = '';
  const bankName = `E2E PW Bank ${marker}`;

  test.beforeAll(async () => {
    if (!isProject('admin')) return;
    adminApi = await ApiClient.as('admin');
    branchId = await adminApi.firstBranchId();
    adminApi.withBranch(branchId);
  });

  test.afterAll(async () => {
    // Deactivation is the only retirement the API offers. Left active, this row
    // would sit in every OM bank picker for every later run.
    if (isProject('admin') && createdBankId) {
      await adminApi.patch(`/banks/${createdBankId}/deactivate`, {}).catch(() => undefined);
    }
    await adminApi?.dispose();
  });

  test('a bank added for a country appears under that country and nowhere else', async ({
    page,
    problems,
  }) => {
    await selectBranch(page, branchId);
    const master = new BankMasterPage(page);
    await master.open();
    await master.selectCountry(COUNTRY);

    expect(await master.canAdd(), 'an admin was not offered the add form').toBe(true);
    await master.add({ name: bankName, bankCode: '099', swift: 'PWTSOMRX' });

    // Read the id back from the server: the point of what follows is that the
    // record exists, not that a row rendered.
    const created = rows(await adminApi.get<BankRecord[]>(`/banks?country=${COUNTRY}`)).find(
      (b) => b.name === bankName,
    );
    expect(created, 'the bank is not on the server after adding it').toBeTruthy();
    createdBankId = created!.id;
    expect(created!.bankCode).toBe('099');

    await master.open();
    await master.selectCountry(COUNTRY);
    await expect.poll(() => master.hasRow(createdBankId), { timeout: 15_000 }).toBe(true);

    // `Bank` is global reference data but it is FILTERED by country, and a
    // filter that leaks is how an employee is offered a bank in the wrong
    // jurisdiction. Switching the picker must drop it.
    await master.selectCountry(OTHER_COUNTRY);
    await expect
      .poll(() => master.hasRow(createdBankId), { timeout: 15_000 })
      .toBe(false);

    settle(problems, 'adding a bank');
  });

  test('an edit rewrites the record, not merely the row', async ({ page, problems }) => {
    test.skip(!createdBankId, 'no bank was added');

    await selectBranch(page, branchId);
    const master = new BankMasterPage(page);
    await master.open();
    await master.selectCountry(COUNTRY);

    await master.edit(createdBankId, { name: `${bankName} (renamed)`, swift: 'PWTSOMR2' });

    await expect
      .poll(
        async () => {
          const all = rows(await adminApi.get<BankRecord[]>(`/banks?country=${COUNTRY}`));
          return all.find((b) => b.id === createdBankId)?.name ?? '';
        },
        { timeout: 15_000 },
      )
      .toBe(`${bankName} (renamed)`);

    settle(problems, 'editing a bank');
  });

  test('deactivating keeps the row on the master and drops it from the pickers', async ({
    page,
    problems,
  }) => {
    test.skip(!createdBankId, 'no bank was added');

    await selectBranch(page, branchId);
    const master = new BankMasterPage(page);
    await master.open();
    await master.selectCountry(COUNTRY);

    expect(await master.isActive(createdBankId)).toBe(true);
    await master.toggleActive(createdBankId);

    // Still listed, greyed. The master is the only view that shows retired
    // banks — losing them here would make an accidental deactivation
    // unrecoverable through the UI.
    await master.expectActive(createdBankId, false);

    // But gone from every consumer, which reads `activeOnly=true`.
    const offered = rows(await adminApi.get<BankRecord[]>(`/banks?country=${COUNTRY}&activeOnly=true`));
    expect(
      offered.map((b) => b.id),
      'a deactivated bank is still offered to employees',
    ).not.toContain(createdBankId);

    settle(problems, 'deactivating a bank');
  });
});

/**
 * The field schema, and the one destructive control in the cluster.
 *
 * A `CountryBankingField` row is what turns a country into a form and what
 * gives the IBAN check something to fire on, so adding one is observable two
 * screens away. The field added here is deliberately NOT required: a required
 * field left behind by a failed run would refuse every migration in the country
 * for every spec that follows.
 */
test.describe('the banking field schema reaches the migration form', () => {
  // Role gate, in a hook rather than in each body: a skip decided here
  // happens before the page fixture is built, so no browser opens.
  test.beforeEach(() => {
    test.skip(!isProject('admin'), 'the field config is admin-only');
  });

  test.describe.configure({ mode: 'serial' });

  let adminApi: ApiClient;
  let branchId = '';
  let candidateId = '';
  let fieldId = '';
  const fieldKey = `pwNote${marker.slice(-4)}`;

  test.beforeAll(async () => {
    if (!isProject('admin')) return;
    adminApi = await ApiClient.as('admin');
    branchId = await adminApi.firstBranchId();
    adminApi.withBranch(branchId);
    const hired = await hireCandidate(adminApi, branchId, `${marker.slice(-5).toUpperCase()}F`).catch(
      () => null,
    );
    candidateId = hired?.id ?? '';
  });

  test.afterAll(async () => {
    if (isProject('admin')) {
      if (fieldId) await adminApi.delete(`/banking-config/${fieldId}`).catch(() => undefined);
      if (candidateId) {
        await adminApi
          .delete(`/employees/${candidateId}?clearanceOverrideReason=${encodeURIComponent(marker)}`)
          .catch(() => undefined);
      }
    }
    await adminApi?.dispose();
  });

  test('a field added for a country appears on that country\'s migration form', async ({
    page,
    problems,
  }) => {
    await selectBranch(page, branchId);
    const config = new BankConfigPage(page);
    await config.open();
    await config.selectCountry(COUNTRY);

    const before = await config.fieldKeys();
    expect(before, 'the OM schema is empty — the baseline seed did not run').toContain('iban');

    await config.save({
      key: fieldKey,
      label: 'PW Reference Note',
      fieldType: 'TEXT',
      validation: 'NONE',
      placeholder: 'Anything',
      order: 9,
      required: false,
      sensitive: false,
    });

    await expect.poll(() => config.fieldKeys(), { timeout: 15_000 }).toContain(fieldKey);
    fieldId = (await config.idForKey(fieldKey)) ?? '';
    expect(fieldId, 'the new field has no id on the row').toBeTruthy();

    // The claim: configuration reaches the form. Without this the config screen
    // is a CRUD table that proves nothing about the product.
    test.skip(!candidateId, 'no candidate to render the form for');
    const migrate = new BankMigratePage(page);
    await migrate.open();
    expect(
      await migrate.fieldKeys(candidateId),
      'a configured field never reached the migration form',
    ).toContain(fieldKey);

    settle(problems, 'adding a banking field');
  });

  test('the key is fixed once the field exists', async ({ page, problems }) => {
    test.skip(!fieldId, 'no field was added');

    await selectBranch(page, branchId);
    const config = new BankConfigPage(page);
    await config.open();
    await config.selectCountry(COUNTRY);
    await config.startEdit(fieldId);

    // Every stored `EmployeeBankDetail.data` blob is keyed by this string.
    // Renaming it would orphan the values under the old key with no migration
    // and no warning, so the screen makes it unreachable rather than merely
    // discouraged.
    expect(await config.keyIsLocked(), 'the field key was editable on an existing row').toBe(true);

    settle(problems, 'editing a banking field');
  });

  test('deleting a field goes through a NATIVE confirm', async ({ page, problems }) => {
    test.skip(!fieldId, 'no field was added');

    // This screen still uses the browser's own dialog rather than the app's
    // ConfirmModal. Playwright DISMISSES those by default, which turns the
    // click into a silent no-op and makes the failure look like a broken
    // backend — so the handler goes on before the click.
    await acceptNativeDialogs(page);

    await selectBranch(page, branchId);
    const config = new BankConfigPage(page);
    await config.open();
    await config.selectCountry(COUNTRY);

    await config.delete(fieldId);

    await expect.poll(() => config.fieldKeys(), { timeout: 15_000 }).not.toContain(fieldKey);

    const remaining = rows(
      await adminApi.get<Array<{ fieldKey: string }>>(`/banking-config?country=${COUNTRY}`),
    );
    expect(remaining.map((f) => f.fieldKey), 'the field survived the delete on the server').not.toContain(
      fieldKey,
    );
    fieldId = '';

    settle(problems, 'deleting a banking field');
  });
});

/**
 * HR meets the two ADMIN-only screens.
 *
 * `/dashboard/banks` and `/dashboard/banks/config` are the only two routes in
 * the app whose guard has to deny an AUTHENTICATED non-admin — everywhere else
 * the denial branch is never taken — which is why they were the only two that
 * ever exposed the React #310 crash. See the comment on those entries in
 * `e2e/routes.ts` and the one at the top of `components/auth/ProtectedRoute.tsx`.
 */
test.describe('HR is refused the admin-only bank screens', () => {
  // Role gate, in a hook rather than in each body: a skip decided here
  // happens before the page fixture is built, so no browser opens.
  test.beforeEach(() => {
    test.skip(!isProject('hr'), 'the denial half, from HR');
  });

  test.describe.configure({ mode: 'serial' });

  const ADMIN_ONLY = ['/dashboard/banks', '/dashboard/banks/config'];

  for (const path of ADMIN_ONLY) {
    test(`${path} sends HR to /403 rather than crashing`, async ({ page, problems }) => {
      /**
       * KNOWN GAP — historical, and asserted at its FIXED behaviour.
       *
       * `e2e/routes.ts` used to carry a `knownBroken` annotation on exactly
       * these two paths: `ProtectedRoute` called `redirect()` from a Client
       * Component's render body, React retried the partially-rendered tree and
       * threw *Minified React error #310 — rendered more hooks than during the
       * previous render*, so an HR user who should have seen /403 saw a crashed
       * page instead.
       *
       * That annotation is gone: the `/dashboard/banks` and
       * `/dashboard/banks/config` entries in `e2e/routes.ts` now carry no
       * `knownBroken`, and the comment above them reads "Now it navigates from
       * an effect, so denial reaches /403 like everywhere else" — matching
       * `ProtectedRoute`, which redirects from `useEffect`. This
       * test therefore asserts the FIXED behaviour — a clean redirect, no
       * uncaught render — which is what keeps the fix from silently regressing.
       * If it fails with a #310 in `pageErrors`, the annotation belongs back in
       * routes.ts and this comment is the record of why.
       */
      await page.goto(path, { waitUntil: 'domcontentloaded' });
      await page.waitForLoadState('networkidle').catch(() => {});

      // Polled, because the denial is a CLIENT-side navigation from an effect
      // and `networkidle` says nothing about whether it has happened — and that
      // promise's rejection is swallowed above, so a sampled read here would be
      // deciding on whatever frame it happened to catch.
      await expect
        .poll(() => new URL(page.url()).pathname, { timeout: 15_000 })
        .toBe('/403');
      expect(
        problems.pageErrors.join('\n'),
        `${path} threw during render for HR — the React #310 regression`,
      ).not.toMatch(/Minified React error #310|rendered more hooks/i);

      settle(problems, path);
    });
  }

  test('HR keeps the two screens the migration flow actually needs', async ({ page, problems }) => {
    // The narrowing is deliberate, not blanket: HR administers bank details but
    // does not define the reference data behind them. Refusing HR the migration
    // screen too would make the whole flow admin-only, which is not the rule the
    // role matrix states (migration candidates / migrate: ADMIN and HR).
    const hrApi = await ApiClient.as('hr');
    try {
      const branchId = await hrApi.firstBranchId();
      await selectBranch(page, branchId);

      for (const path of ['/dashboard/banks/migrate', '/dashboard/banks/branch-countries']) {
        await page.goto(path, { waitUntil: 'domcontentloaded' });
        await page.waitForLoadState('networkidle').catch(() => {});
        expect(new URL(page.url()).pathname, `${path} refused HR, who administers it`).toBe(path);
      }

      // And the server agrees — a client guard that admits a role the API
      // refuses is a screen that can only fail.
      const candidates = rows(
        await hrApi.get<Candidate[]>('/bank-change-requests/migration/candidates'),
      );
      expect(Array.isArray(candidates), 'HR could not read the migration candidates').toBe(true);
    } finally {
      await hrApi.dispose();
    }

    settle(problems, 'HR on the migration screens');
  });
});
