import * as bcrypt from 'bcrypt';
import { bootE2EApp, E2EContext } from './utils/e2e-app';

/**
 * Daily-wage payroll + Overtime Policy engine, end to end against the real DB.
 *
 * Drives the whole lifecycle over HTTP for a freshly onboarded daily-wage
 * employee — create employee → assign an employment-type policy → register
 * overtime on a weekday, a rest day and a public holiday → approve → generate
 * payroll → read the payslip — and asserts the money at every step.
 *
 * The two defects this locks down:
 *
 *  1. **Daily-wage salary.** `Employee.baseSalary` holds a PER-DAY rate when
 *     `salaryType = DAILY`. The engine used to read every base salary as a
 *     monthly amount, so a 30/day worker was paid 30 for the month and their
 *     overtime hour was priced at 30/(workDays×8) ≈ 0.14 instead of 30/8 = 3.75.
 *  2. **Policy resolution.** A daily-wage policy with `holidayBehavior: IGNORE`
 *     must collapse a public holiday to an ordinary working day (no premium),
 *     while a monthly colleague on the Company Default still gets the holiday
 *     tier for the same date.
 *
 * Every expected figure below is independent of how many work days the month
 * happens to hold — which is precisely the property the fix restores.
 */
describe('Daily-wage payroll & Overtime Policy (e2e)', () => {
  let ctx: E2EContext;
  const PASSWORD = 'Passw0rd!';
  const runId = `dw${Date.now()}`;

  // A month far enough out that no seeded/demo payroll can collide with it.
  const MONTH = 11;
  const YEAR = 2029;
  const DAILY_RATE = 30; // per day
  const MONTHLY_RATE = 1200; // per month
  const PRESENT_DAYS = 22;
  const HOURS_PER_DAY = 8;
  /** hourlyRate for the daily-wage employee = 30 / 8 */
  const DW_HOURLY = DAILY_RATE / HOURS_PER_DAY;

  const emails = {
    admin: `admin-${runId}@test.local`,
  };

  let adminToken: string;
  let branchId: string;
  let deptId: string;
  let dailyEmpId: string;
  let monthlyEmpId: string;
  let policyId: string;
  const createdPayrollIds: string[] = [];

  const EMP_TYPE = `Daily Wage ${runId}`;
  const ymd = (d: Date) => d.toISOString().slice(0, 10);
  /** A UTC instant on `date` at HH:MM — OT times are tz-naive wall clock. */
  const at = (date: Date, hh: number, mm = 0) =>
    new Date(
      Date.UTC(
        date.getUTCFullYear(),
        date.getUTCMonth(),
        date.getUTCDate(),
        hh,
        mm,
      ),
    ).toISOString();

  /** The nth (1-based) day of MONTH/YEAR falling on `weekday` (0 = Sunday). */
  const nthWeekday = (weekday: number, nth = 1): Date => {
    let seen = 0;
    for (let day = 1; day <= 31; day++) {
      const d = new Date(Date.UTC(YEAR, MONTH - 1, day));
      if (d.getUTCMonth() !== MONTH - 1) break;
      if (d.getUTCDay() === weekday && ++seen === nth) return d;
    }
    throw new Error(`no weekday ${weekday} #${nth} in ${MONTH}/${YEAR}`);
  };

  // Branch works Mon–Sat; Sunday (0) is the only weekly off.
  const WEEKDAY_OT_DATE = nthWeekday(3, 1); // a Wednesday
  const REST_DAY_OT_DATE = nthWeekday(0, 2); // a Sunday
  const HOLIDAY_OT_DATE = nthWeekday(4, 2); // a Thursday, made a public holiday

  const api = () => ctx.http();
  const asAdmin = (req: any) =>
    req.set('Authorization', `Bearer ${adminToken}`).set('x-branch-id', branchId);

  beforeAll(async () => {
    ctx = await bootE2EApp();
    const { prisma } = ctx;

    const branch = await prisma.branch.create({
      data: {
        code: `DW-BR-${runId}`,
        name: 'Daily Wage Site',
        isActive: true,
        timezone: 'Asia/Kolkata',
        officeStartTime: '08:30',
        officeEndTime: '17:00',
        weeklyOffDays: '0', // Sunday only — deterministic rest day
      },
    });
    branchId = branch.id;

    const dept = await prisma.department.create({
      data: { code: `DW-D-${runId}`, name: `DW Dept ${runId}`, isActive: true },
    });
    deptId = dept.id;

    await prisma.user.create({
      data: {
        email: emails.admin,
        passwordHash: await bcrypt.hash(PASSWORD, 10),
        role: 'ADMIN',
        isActive: true,
        isGlobalBranchAccess: true,
      },
    });

    const login = await api()
      .post('/auth/login')
      .send({ email: emails.admin, password: PASSWORD });
    adminToken = login.body?.data?.accessToken;
    expect(adminToken).toBeTruthy();

    // A public holiday on the branch, for the holidayBehavior test.
    await prisma.holiday.create({
      data: {
        name: `DW Holiday ${runId}`,
        date: HOLIDAY_OT_DATE,
        year: YEAR,
        branchId,
      },
    });
  });

  afterAll(async () => {
    const { prisma } = ctx;
    // Employee codes are auto-generated by the API, so identify this run's
    // employees by their runId-tagged e-mail instead.
    const employeeIds = (
      await prisma.employee.findMany({
        where: { email: { contains: runId } },
        select: { id: true },
      })
    ).map((e) => e.id);
    const empWhere = { employeeId: { in: employeeIds } };

    // EMPLOYMENT_TYPE rows are global, not branch-scoped, so a run that leaves
    // its own behind pollutes the shared dev database for every later run.
    await prisma.libraryItem.deleteMany({
      where: { libraryType: 'EMPLOYMENT_TYPE', label: { contains: runId } },
    });

    await prisma.payrollItem.deleteMany({ where: empWhere });
    await prisma.payroll.deleteMany({ where: { branchId } });
    if (createdPayrollIds.length) {
      await prisma.payroll.deleteMany({
        where: { id: { in: createdPayrollIds } },
      });
    }
    // Approval trail rows key off requestId with no FK, so they must be removed
    // explicitly or they outlive the requests they describe.
    const otIds = (
      await prisma.overtimeRequest.findMany({
        where: empWhere,
        select: { id: true },
      })
    ).map((o) => o.id);
    if (otIds.length) {
      await prisma.requestApproval.deleteMany({
        where: { requestId: { in: otIds } },
      });
    }
    await prisma.overtimeRequest.deleteMany({ where: empWhere });
    await prisma.attendance.deleteMany({ where: empWhere });
    await prisma.salaryComponent.deleteMany({ where: empWhere });
    await prisma.employeeHistory.deleteMany({ where: empWhere });
    await prisma.holiday.deleteMany({ where: { name: { contains: runId } } });
    await prisma.user.deleteMany({ where: { email: { contains: runId } } });
    await prisma.employee.deleteMany({ where: { id: { in: employeeIds } } });
    await prisma.overtimePolicy.deleteMany({
      where: { name: { contains: runId } },
    });
    await prisma.department.deleteMany({ where: { code: { contains: runId } } });
    await prisma.branch.deleteMany({ where: { code: { contains: runId } } });
    await ctx.app.close();
  });

  // ── 1. Onboarding ────────────────────────────────────────────────────────
  describe('1. sample employees', () => {
    it('creates a DAILY-wage employee whose baseSalary is a per-day rate', async () => {
      const res = await asAdmin(api().post('/employees')).send({
        fullName: `Daily Wager ${runId}`,
        dateOfBirth: '1992-04-11',
        idCard: `DW-ID-${runId}`,
        email: `daily-${runId}@test.local`,
        departmentId: deptId,
        branchId,
        position: 'Site Worker',
        startDate: '2026-01-01',
        baseSalary: DAILY_RATE,
        salaryType: 'DAILY',
        employmentType: EMP_TYPE,
      });
      expect(res.status).toBe(201);
      dailyEmpId = res.body.data.id;
      expect(res.body.data.salaryType).toBe('DAILY');
      expect(Number(res.body.data.baseSalary)).toBe(DAILY_RATE);
    });

    it('creates a MONTHLY colleague as the control', async () => {
      const res = await asAdmin(api().post('/employees')).send({
        fullName: `Monthly Staff ${runId}`,
        dateOfBirth: '1990-02-02',
        idCard: `MO-ID-${runId}`,
        email: `monthly-${runId}@test.local`,
        departmentId: deptId,
        branchId,
        position: 'Supervisor',
        startDate: '2026-01-01',
        baseSalary: MONTHLY_RATE,
        employmentType: `Monthly ${runId}`,
      });
      expect(res.status).toBe(201);
      monthlyEmpId = res.body.data.id;
      // Omitting salaryType must keep the legacy monthly meaning.
      expect(res.body.data.salaryType).toBe('MONTHLY');
    });

    it('rejects an unknown salaryType', async () => {
      const res = await asAdmin(api().post('/employees')).send({
        fullName: 'Bad Basis',
        dateOfBirth: '1990-02-02',
        idCard: `BAD-ID-${runId}`,
        email: `bad-${runId}@test.local`,
        departmentId: deptId,
        branchId,
        position: 'X',
        startDate: '2026-01-01',
        baseSalary: 10,
        salaryType: 'HOURLY',
      });
      expect(res.status).toBe(400);
    });

    it('switching an employee to DAILY is recorded in their history', async () => {
      await asAdmin(api().patch(`/employees/${monthlyEmpId}`)).send({
        salaryType: 'DAILY',
      });
      const history = await ctx.prisma.employeeHistory.findMany({
        where: { employeeId: monthlyEmpId, field: 'salaryType' },
      });
      expect(history).toHaveLength(1);
      expect(history[0].newValue).toBe('DAILY');
      // Put the control employee back on a monthly basis.
      await asAdmin(api().patch(`/employees/${monthlyEmpId}`)).send({
        salaryType: 'MONTHLY',
      });
    });
  });

  // ── 2. Policy resolution ─────────────────────────────────────────────────
  describe('2. overtime policy resolution', () => {
    it('a Company Default policy exists without anyone creating one', async () => {
      const res = await asAdmin(api().get('/overtime-policies'));
      expect(res.status).toBe(200);
      const def = res.body.data.find((p: any) => p.isDefault && p.isActive);
      expect(def).toBeDefined();
    });

    it('the monthly employee falls through to the Company Default', async () => {
      const res = await asAdmin(
        api().get(`/overtime-policies/resolve/${monthlyEmpId}`),
      );
      expect(res.status).toBe(200);
      expect(res.body.data.source).toBe('COMPANY_DEFAULT');
      expect(res.body.data.holidayBehavior).toBe('STANDARD');
    });

    it('ADMIN creates a daily-wage policy that ignores public holidays', async () => {
      const res = await asAdmin(api().post('/overtime-policies')).send({
        name: `Daily Wage OT ${runId}`,
        description: 'Holidays are ordinary working days for daily-wage staff',
        employmentType: EMP_TYPE,
        rules: {
          holidayBehavior: 'IGNORE',
          regularRate: 1.5,
          lateRate: 2,
          doubleRate: 2,
          lateThreshold: '22:00',
          shiftEndTime: '17:00',
          dayEndBoundary: '23:59',
          sunday: { regularRate: 2, lateRate: 2, lateThreshold: '22:00' },
          holiday: { regularRate: 2, lateRate: 2, lateThreshold: '22:00' },
          foodAllowanceEnabled: false,
          maxHoursPerDay: 8,
          maxHoursPerDoubleDay: 12,
          maxHoursPerMonth: 200,
          maxHoursPerYear: 1000,
        },
      });
      expect(res.status).toBe(201);
      policyId = res.body.data.id;
    });

    it('the daily-wage employee resolves to it by employment type', async () => {
      const res = await asAdmin(
        api().get(`/overtime-policies/resolve/${dailyEmpId}`),
      );
      expect(res.status).toBe(200);
      expect(res.body.data.source).toBe('EMPLOYMENT_TYPE');
      expect(res.body.data.effectivePolicyId).toBe(policyId);
      expect(res.body.data.holidayBehavior).toBe('IGNORE');
      expect(res.body.data.eligible).toBe(true);
    });

    it('a second active policy for the same employment type is rejected', async () => {
      const res = await asAdmin(api().post('/overtime-policies')).send({
        name: `Clashing ${runId}`,
        employmentType: EMP_TYPE,
      });
      expect(res.status).toBe(409);
    });

    it('the active default cannot be deactivated out from under everyone', async () => {
      const list = await asAdmin(api().get('/overtime-policies'));
      const def = list.body.data.find((p: any) => p.isDefault && p.isActive);
      const res = await asAdmin(
        api().patch(`/overtime-policies/${def.id}/active`),
      ).send({ isActive: false });
      expect(res.status).toBe(400);
    });
  });

  // ── 3. Overtime classification ───────────────────────────────────────────
  describe('3. overtime registration & approval', () => {
    const registerAndApprove = async (
      employeeId: string,
      date: Date,
      startHour: number,
      endHour: number,
    ) => {
      const created = await asAdmin(
        api().post(`/overtime/employee/${employeeId}`),
      ).send({
        date: ymd(date),
        startTime: at(date, startHour),
        endTime: at(date, endHour),
        hours: endHour - startHour,
        reason: `e2e ${runId}`,
      });
      expect([200, 201]).toContain(created.status);
      const id = created.body?.data?.id ?? created.body?.id;
      const approved = await asAdmin(api().post(`/overtime/${id}/approve`));
      expect([200, 201]).toContain(approved.status);
      return approved.body?.data ?? approved.body;
    };

    it('weekday 18:00–23:00 splits 4h regular + 1h late, stamped with the policy', async () => {
      const ot = await registerAndApprove(dailyEmpId, WEEKDAY_OT_DATE, 18, 23);
      expect(ot.dayType).toBe('WEEKDAY');
      expect(ot.otType).toBe('LATE');
      expect(Number(ot.regularHours)).toBe(4); // 18:00–22:00
      expect(Number(ot.lateHours)).toBe(1); //    22:00–23:00
      expect(ot.overtimePolicyId).toBe(policyId);
    });

    it('a Sunday is a rest day → the double tier still applies', async () => {
      const ot = await registerAndApprove(dailyEmpId, REST_DAY_OT_DATE, 18, 21);
      expect(ot.dayType).toBe('SUNDAY');
      expect(Number(ot.doubleHours)).toBe(3);
    });

    it('holidayBehavior IGNORE collapses a public holiday to a plain weekday', async () => {
      const ot = await registerAndApprove(dailyEmpId, HOLIDAY_OT_DATE, 18, 20);
      expect(ot.dayType).toBe('WEEKDAY');
      expect(Number(ot.regularHours)).toBe(2);
      expect(Number(ot.doubleHours)).toBe(0);
    });

    it('the same holiday IS a holiday for the monthly colleague (STANDARD)', async () => {
      const ot = await registerAndApprove(monthlyEmpId, HOLIDAY_OT_DATE, 18, 20);
      expect(ot.dayType).toBe('HOLIDAY');
      expect(Number(ot.doubleHours)).toBe(2);
    });
  });

  // ── 4. Payroll ───────────────────────────────────────────────────────────
  describe('4. payroll run', () => {
    let dailyItem: any;
    let monthlyItem: any;

    beforeAll(async () => {
      const { prisma } = ctx;
      // PRESENT attendance for the daily-wage employee on the first
      // PRESENT_DAYS non-Sunday dates of the month.
      const dates: Date[] = [];
      for (let day = 1; dates.length < PRESENT_DAYS && day <= 31; day++) {
        const d = new Date(Date.UTC(YEAR, MONTH - 1, day));
        if (d.getUTCMonth() !== MONTH - 1) break;
        if (d.getUTCDay() !== 0) dates.push(d);
      }
      await prisma.attendance.createMany({
        data: dates.flatMap((date) =>
          [dailyEmpId, monthlyEmpId].map((employeeId) => ({
            employeeId,
            date,
            status: 'PRESENT',
            // Attendance carries a denormalized branch — payroll's
            // "was attendance processed?" probe is branch-scoped on it.
            branchId,
          })),
        ),
      });

      const res = await asAdmin(api().post('/payrolls')).send({
        month: MONTH,
        year: YEAR,
      });
      expect(res.status).toBe(201);
      createdPayrollIds.push(res.body.data.id);

      const items = await prisma.payrollItem.findMany({
        where: { payrollId: res.body.data.id },
      });
      dailyItem = items.find((i) => i.employeeId === dailyEmpId);
      monthlyItem = items.find((i) => i.employeeId === monthlyEmpId);
      expect(dailyItem).toBeDefined();
      expect(monthlyItem).toBeDefined();
    });

    it('daily-wage base pay is rate × days present', () => {
      expect(Number(dailyItem.baseSalary)).toBe(DAILY_RATE * PRESENT_DAYS); // 660
      expect(Number(dailyItem.actualWorkDays)).toBe(PRESENT_DAYS);
    });

    it('daily-wage staff carry no LOP deduction', () => {
      expect(Number(dailyItem.deduction)).toBe(0);
      expect(dailyItem.notes).toContain(`${PRESENT_DAYS} day(s) worked`);
      expect(dailyItem.notes).not.toContain('Loss of Pay');
    });

    it('the base pay does NOT depend on the month’s work-day count', () => {
      // The regression: baseSalary used to come out as the bare 30/day rate.
      expect(Number(dailyItem.baseSalary)).not.toBe(DAILY_RATE);
      expect(Number(dailyItem.baseSalary)).toBe(
        DAILY_RATE * Number(dailyItem.actualWorkDays),
      );
    });

    it('overtime is priced at dayRate/8, per tier', () => {
      //  weekday : 4h × 1.5 + 1h × 2.0            = 8.0 rate-hours
      //  Sunday  : 3h × 2.0 (sunday.regularRate)  = 6.0
      //  holiday : 2h × 1.5 (IGNORE → weekday)    = 3.0
      //  total   = 17.0 × 3.75/h                  = 63.75
      expect(Number(dailyItem.overtimeHours)).toBe(10);
      expect(Number(dailyItem.overtimePay)).toBeCloseTo(17 * DW_HOURLY, 2);
      expect(Number(dailyItem.overtimePay)).toBeCloseTo(63.75, 2);
    });

    it('regression: the monthly formula would have paid ~1/workDays of that', () => {
      const wrongHourly =
        DAILY_RATE / (Number(dailyItem.workDays) * HOURS_PER_DAY);
      expect(Number(dailyItem.overtimePay) / (17 * wrongHourly)).toBeCloseTo(
        Number(dailyItem.workDays),
        4,
      );
    });

    it('the monthly colleague is still paid a month with LOP proration', () => {
      const workDays = Number(monthlyItem.workDays);
      const lopDays = Math.max(0, workDays - PRESENT_DAYS);
      expect(Number(monthlyItem.baseSalary)).toBe(MONTHLY_RATE);
      expect(Number(monthlyItem.deduction)).toBeCloseTo(
        (MONTHLY_RATE * lopDays) / workDays,
        2,
      );
    });

    it('the payslip endpoint returns the same figures', async () => {
      const res = await asAdmin(
        api().get(`/payrolls/payslip/${dailyEmpId}/${MONTH}/${YEAR}`),
      );
      expect(res.status).toBe(200);
      expect(Number(res.body.data.baseSalary)).toBe(DAILY_RATE * PRESENT_DAYS);
      expect(Number(res.body.data.overtimePay)).toBeCloseTo(63.75, 2);
    });
  });

  // ── 5. Employment Type -> Pay Basis, and the opt-in paid days ────────────
  describe('5. employment type derives the pay basis', () => {
    let libraryItemId: string;

    /** The state from the bug report: daily-wage type, monthly pay basis. */
    it('an EMPLOYMENT_TYPE library item can be flagged DAILY', async () => {
      const created = await asAdmin(api().post('/library-items')).send({
        libraryType: 'EMPLOYMENT_TYPE',
        label: EMP_TYPE,
        isActive: true,
      });
      // The label may already exist from section 2's policy setup.
      if (created.status === 201) {
        libraryItemId = created.body.data.id;
      } else {
        const all = await asAdmin(
          api().get('/library-items').query({ type: 'EMPLOYMENT_TYPE' }),
        );
        libraryItemId = all.body.data.find((i: any) => i.label === EMP_TYPE).id;
      }

      const flagged = await asAdmin(
        api().patch(`/library-items/${libraryItemId}`),
      ).send({ payBasis: 'DAILY' });
      expect(flagged.status).toBe(200);
      expect(flagged.body.data.payBasis).toBe('DAILY');
    });

    it('rejects the flag on a library that would never read it', async () => {
      const res = await asAdmin(api().post('/library-items')).send({
        libraryType: 'POSITION',
        label: `Bad Basis ${runId}`,
        payBasis: 'DAILY',
      });
      expect(res.status).toBe(400);
    });

    it('assigning the flagged type alone flips the employee to DAILY', async () => {
      // The control employee is MONTHLY and stays that way until the employment
      // type — and nothing else — is changed.
      const before = await asAdmin(api().get(`/employees/${monthlyEmpId}`));
      expect(before.body.data.salaryType).toBe('MONTHLY');

      const res = await asAdmin(api().patch(`/employees/${monthlyEmpId}`)).send({
        employmentType: EMP_TYPE,
      });
      expect(res.status).toBe(200);

      const after = await asAdmin(api().get(`/employees/${monthlyEmpId}`));
      expect(after.body.data.salaryType).toBe('DAILY');
    });

    it('the derived flip and its cause are both in the employee history', async () => {
      const history = await ctx.prisma.employeeHistory.findMany({
        where: { employeeId: monthlyEmpId },
        orderBy: { changedAt: 'desc' },
      });
      const fields = history.map((h) => h.field);
      expect(fields).toContain('salaryType');
      expect(fields).toContain('employmentType');
    });

    it('a salaryType that contradicts the flagged type is rejected, not ignored', async () => {
      const res = await asAdmin(api().patch(`/employees/${monthlyEmpId}`)).send({
        salaryType: 'MONTHLY',
      });
      expect(res.status).toBe(400);
      expect(String(res.body.message)).toMatch(/employment type/i);
    });

    it('clearing the employment type leaves the basis alone, never resetting it', async () => {
      // Resetting would silently re-read a per-day rate as a monthly salary.
      const res = await asAdmin(api().patch(`/employees/${monthlyEmpId}`)).send({
        employmentType: '',
      });
      expect(res.status).toBe(200);
      const after = await asAdmin(api().get(`/employees/${monthlyEmpId}`));
      expect(after.body.data.salaryType).toBe('DAILY');

      // Restore the control employee for any later assertions.
      await asAdmin(api().patch(`/employees/${monthlyEmpId}`)).send({
        salaryType: 'MONTHLY',
      });
    });

    it('the three daily-wage settings are exposed in the settings catalogue', async () => {
      const res = await asAdmin(api().get('/system-settings'));
      expect(res.status).toBe(200);
      const keys = res.body.data.map((s: any) => s.key);
      expect(keys).toEqual(
        expect.arrayContaining([
          'payroll_daily_wage_statutory_deductions',
          'payroll_daily_wage_pay_leave',
          'payroll_daily_wage_pay_holidays',
        ]),
      );
      // Both new keys default to off, preserving the days-worked-only rule.
      const value = (k: string) =>
        res.body.data.find((s: any) => s.key === k)?.value;
      expect(value('payroll_daily_wage_pay_leave')).toBe('false');
      expect(value('payroll_daily_wage_pay_holidays')).toBe('false');
    });
  });

  // ── 6. Paying daily-wage staff for public holidays ───────────────────────
  describe('6. opt-in paid public holidays', () => {
    /** A working day of the month, chosen so it is neither Sunday nor attended. */
    let holidayDate: Date;
    let baseline = 0;

    beforeAll(async () => {
      // A date AFTER the PRESENT_DAYS block, so it is a genuinely unworked day.
      for (let day = 31; day >= 1; day--) {
        const d = new Date(Date.UTC(YEAR, MONTH - 1, day));
        if (d.getUTCMonth() !== MONTH - 1) continue;
        if (d.getUTCDay() === 0) continue;
        const attended = await ctx.prisma.attendance.findFirst({
          where: { employeeId: dailyEmpId, date: d },
        });
        if (!attended) {
          holidayDate = d;
          break;
        }
      }
      const item = await ctx.prisma.payrollItem.findFirst({
        where: { employeeId: dailyEmpId, payrollId: { in: createdPayrollIds } },
      });
      baseline = Number(item?.baseSalary ?? 0);
    });

    const rerunPayroll = async () => {
      for (const id of createdPayrollIds.splice(0)) {
        await asAdmin(api().delete(`/payrolls/${id}`));
      }
      const res = await asAdmin(api().post('/payrolls')).send({
        month: MONTH,
        year: YEAR,
      });
      expect(res.status).toBe(201);
      createdPayrollIds.push(res.body.data.id);
      return ctx.prisma.payrollItem.findFirst({
        where: { payrollId: res.body.data.id, employeeId: dailyEmpId },
      });
    };

    it('the baseline is days actually worked, nothing more', () => {
      expect(baseline).toBe(DAILY_RATE * PRESENT_DAYS);
    });

    it('a public holiday is still unpaid while the setting is off', async () => {
      await ctx.prisma.holiday.create({
        data: {
          name: `DW Paid Holiday ${runId}`,
          date: holidayDate,
          year: YEAR,
          branchId,
        },
      });
      const item = await rerunPayroll();
      expect(Number(item!.baseSalary)).toBe(baseline);
    });

    it('turning the setting on pays the day rate for that holiday', async () => {
      const res = await asAdmin(api().post('/system-settings')).send({
        settings: { payroll_daily_wage_pay_holidays: 'true' },
      });
      expect([200, 201]).toContain(res.status);

      const item = await rerunPayroll();
      expect(Number(item!.baseSalary)).toBe(baseline + DAILY_RATE);
      expect(Number(item!.actualWorkDays)).toBe(PRESENT_DAYS + 1);
      expect(item!.notes).toContain('public holidays 1');
    });

    afterAll(async () => {
      // Leave the shared DEV database exactly as it was found — this key is
      // global, so leaving it on would change every later payroll run.
      await asAdmin(api().post('/system-settings')).send({
        settings: { payroll_daily_wage_pay_holidays: 'false' },
      });
      await ctx.prisma.holiday.deleteMany({
        where: { name: `DW Paid Holiday ${runId}` },
      });
    });
  });


  // ── 7. The Taneka production incident (Aug 2026) ─────────────────────────
  //
  // Two independent misconfigurations each made ordinary weekday evening
  // overtime bill at a premium, and neither was visible on the request form:
  //
  //  1. The branch was saved with weeklyOffDays "1,2,3,4,5,6" — the WORKING
  //     days entered into the OFF-days field — so every Mon–Sat classified as
  //     a rest day and paid DOUBLE_LATE at 2x.
  //  2. The governing policy stored lateThreshold "11:59" meaning 11:59 PM.
  //     The threshold landed behind the 17:00 overtime start, the regular tier
  //     collapsed to zero hours, and every hour billed LATE.
  //
  // Both are pinned here over HTTP, against the real database.
  describe('7. weekday evening overtime is not silently premium-rated', () => {
    const INCIDENT_EMP_TYPE = `Incident Wage ${runId}`;
    const FRIDAY_OT_DATE = nthWeekday(5, 3);
    let incidentEmpId: string;

    beforeAll(async () => {
      // A policy shaped exactly like the production "Daily Wages" one, but with
      // the pre-noon late threshold that caused the incident.
      const policy = await asAdmin(api().post('/overtime-policies')).send({
        name: `Incident OT ${runId}`,
        description: 'Pre-noon late threshold, as stored in production',
        employmentType: INCIDENT_EMP_TYPE,
        rules: {
          holidayBehavior: 'IGNORE',
          regularRate: 1.5,
          lateRate: 2,
          doubleRate: 2,
          lateThreshold: '11:59', // 11:59 PM was intended
          shiftEndTime: '17:00',
          dayEndBoundary: '05:00',
          sunday: { regularRate: 1.5, lateRate: 2, lateThreshold: '17:00' },
          holiday: { regularRate: 1.5, lateRate: 2, lateThreshold: '17:00' },
          doubleOtEnabled: true,
          doubleOtAllowAnytime: true,
          foodAllowanceEnabled: false,
          maxHoursPerDay: 8,
          maxHoursPerDoubleDay: 12,
          maxHoursPerMonth: 200,
          maxHoursPerYear: 1000,
        },
      });
      expect([200, 201]).toContain(policy.status);

      const emp = await asAdmin(api().post('/employees')).send({
        fullName: `Incident Worker ${runId}`,
        dateOfBirth: '1994-03-03',
        idCard: `INC-ID-${runId}`,
        email: `incident-${runId}@test.local`,
        departmentId: deptId,
        branchId,
        position: 'Site Worker',
        startDate: '2026-01-01',
        baseSalary: DAILY_RATE,
        salaryType: 'DAILY',
        employmentType: INCIDENT_EMP_TYPE,
      });
      expect(emp.status).toBe(201);
      incidentEmpId = emp.body.data.id;
    });

    it('a pre-noon late threshold does not make a 17:00–22:00 Friday late', async () => {
      const created = await asAdmin(
        api().post(`/overtime/employee/${incidentEmpId}`),
      ).send({
        date: ymd(FRIDAY_OT_DATE),
        startTime: at(FRIDAY_OT_DATE, 17),
        endTime: at(FRIDAY_OT_DATE, 22),
        hours: 5,
        reason: `e2e incident ${runId}`,
      });
      expect([200, 201]).toContain(created.status);
      const id = created.body?.data?.id ?? created.body?.id;

      const approved = await asAdmin(api().post(`/overtime/${id}/approve`));
      expect([200, 201]).toContain(approved.status);
      const ot = approved.body?.data ?? approved.body;

      // Friday is a working day on this branch (weeklyOffDays "0"), and the
      // 11:59 threshold rolls to the next day under the noon rule.
      expect(ot.dayType).toBe('WEEKDAY');
      expect(ot.otType).toBe('REGULAR');
      expect(Number(ot.regularHours)).toBe(5);
      expect(Number(ot.lateHours)).toBe(0);
      expect(Number(ot.doubleHours)).toBe(0);
      expect(Number(ot.doubleLateHours)).toBe(0);
    });

    it('refuses a weekly-off set covering all seven days', async () => {
      const res = await asAdmin(api().patch(`/branches/${branchId}`)).send({
        weeklyOffDays: '0,1,2,3,4,5,6',
      });
      expect(res.status).toBe(400);

      // And the branch is untouched — a refused save must not half-apply.
      const branch = await ctx.prisma.branch.findUnique({
        where: { id: branchId },
      });
      expect(branch?.weeklyOffDays).toBe('0');
    });

    it('normalises a weekly-off set instead of storing it as typed', async () => {
      const res = await asAdmin(api().patch(`/branches/${branchId}`)).send({
        weeklyOffDays: '6,0,0',
      });
      expect(res.status).toBe(200);
      expect(res.body.data.weeklyOffDays).toBe('0,6');

      // Put the branch back to the Sunday-only roster the rest of the suite
      // depends on.
      const restored = await asAdmin(api().patch(`/branches/${branchId}`)).send({
        weeklyOffDays: '0',
      });
      expect(restored.status).toBe(200);
      expect(restored.body.data.weeklyOffDays).toBe('0');
    });

    it('an inverted weekly-off set is what turns a Friday into rest-day pay', async () => {
      // The mechanism itself, proved rather than asserted from the incident
      // report: with Mon–Sat marked off, the same Friday flips to the double
      // tier. This is why the branch form now reads the working days back.
      const inverted = await asAdmin(api().patch(`/branches/${branchId}`)).send({
        weeklyOffDays: '1,2,3,4,5,6',
      });
      expect(inverted.status).toBe(200);

      try {
        const anotherFriday = nthWeekday(5, 4);
        const created = await asAdmin(
          api().post(`/overtime/employee/${incidentEmpId}`),
        ).send({
          date: ymd(anotherFriday),
          startTime: at(anotherFriday, 17),
          endTime: at(anotherFriday, 22),
          hours: 5,
          reason: `e2e inverted ${runId}`,
        });
        expect([200, 201]).toContain(created.status);
        const id = created.body?.data?.id ?? created.body?.id;
        const approved = await asAdmin(api().post(`/overtime/${id}/approve`));
        expect([200, 201]).toContain(approved.status);
        const ot = approved.body?.data ?? approved.body;

        // Exactly what production showed: a Friday priced as rest-day work,
        // and late from the first minute because the rest-day tier's own
        // threshold is 17:00.
        expect(ot.dayType).toBe('SUNDAY');
        expect(ot.otType).toBe('DOUBLE_LATE');
        expect(Number(ot.doubleLateHours)).toBe(5);
      } finally {
        // Restore the roster the rest of the suite depends on, whatever the
        // assertions above did.
        const restored = await asAdmin(
          api().patch(`/branches/${branchId}`),
        ).send({ weeklyOffDays: '0' });
        expect(restored.status).toBe(200);
        expect(restored.body.data.weeklyOffDays).toBe('0');
      }
    });
  });

});
