import { ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { StorageService } from '../storage/storage.service';
import { assertInBranch } from '../common/branch/branch-scope.util';

export type VaultKind =
  | 'PERSONAL'
  | 'LETTER'
  | 'LEGAL'
  | 'CONTRACT'
  | 'PAYSLIP'
  | 'CERTIFICATE';

export interface VaultItem {
  id: string;
  kind: VaultKind;
  title: string;
  category: string;
  issueDate: string | null;
  expiryDate: string | null;
  /** Days until expiry; negative once lapsed. Null when it never expires. */
  daysUntilExpiry: number | null;
  /** Public URL, or null when the file is private and needs the download route. */
  fileUrl: string | null;
  /** Route to fetch a private file: /secure-files/{kind}/{id}. */
  secureKind: string | null;
  secureId: string | null;
  source: string;
}

/**
 * One screen for everything an employee holds.
 *
 * Deliberately no new table: personal documents, generated letters, visa records,
 * contracts and payslips already exist and are already the source of truth. A
 * vault table would be a fifth copy that could only drift. This aggregates the
 * four read paths into one shape.
 */
@Injectable()
export class DocumentVaultService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly storage: StorageService,
  ) {}

  private daysUntil(d: Date | null): number | null {
    if (!d) return null;
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    return Math.ceil((new Date(d).getTime() - today.getTime()) / 86_400_000);
  }

  /**
   * An employee reads their own vault; HR reads anyone's. A MANAGER is
   * deliberately NOT given departmental access — a vault holds salary
   * certificates and passport scans, which a line manager has no business
   * reading.
   */
  private assertMayRead(employeeId: string, user: any) {
    if (employeeId === user?.employeeId) return;
    if (['ADMIN', 'HR_MANAGER'].includes(user?.role)) return;
    throw new ForbiddenException('You can only view your own documents');
  }

  async forEmployee(employeeId: string, user: any) {
    this.assertMayRead(employeeId, user);

    const employee = await this.prisma.employee.findUnique({
      where: { id: employeeId },
      select: { id: true, branchId: true },
    });
    if (!employee) throw new NotFoundException('Employee not found');

    // Your own vault is yours whatever branch you happen to be LOOKING at.
    //
    // The branch selector is a view filter over company data, not a statement
    // about who you are — so applying it here meant an admin whose own record
    // sits in Head Office got a 404 on /document-vault/me the moment they
    // switched the picker to another branch. Their payslips and passport scans
    // simply vanished, with no explanation, on a screen called "My Documents".
    //
    // Reading SOMEONE ELSE's vault stays branch-scoped: that is company data,
    // and `assertMayRead` above has already restricted it to ADMIN/HR.
    const isSelf = employeeId === user?.employeeId;
    if (!isSelf) assertInBranch(employee.branchId);

    const [documents, legalDocs, contracts, payslips] = await Promise.all([
      this.prisma.employeeDocument.findMany({
        where: { employeeId },
        orderBy: { uploadedAt: 'desc' },
      }),
      this.prisma.employeeLegalDocument.findMany({
        where: { employeeId },
        orderBy: { expiryDate: 'desc' },
      }),
      this.prisma.contract.findMany({
        where: { employeeId },
        select: {
          id: true,
          contractNumber: true,
          contractType: true,
          startDate: true,
          endDate: true,
          status: true,
        },
        orderBy: { startDate: 'desc' },
      }),
      this.prisma.payrollItem.findMany({
        where: { employeeId },
        select: {
          id: true,
          payroll: { select: { month: true, year: true, status: true } },
        },
        orderBy: { createdAt: 'desc' },
        take: 24,
      }),
    ]);

    const items: VaultItem[] = [];

    for (const doc of documents) {
      // AVATAR is a profile picture, not a document.
      if (doc.documentType === 'AVATAR') continue;
      const isPrivate = StorageService.isPrivateRef(doc.privateRef ?? doc.fileUrl);
      items.push({
        id: doc.id,
        kind: doc.isSystemGenerated ? 'LETTER' : 'PERSONAL',
        title: doc.fileName,
        category: doc.documentType,
        issueDate: doc.issueDate?.toISOString() ?? doc.uploadedAt.toISOString(),
        expiryDate: doc.expiryDate?.toISOString() ?? null,
        daysUntilExpiry: this.daysUntil(doc.expiryDate),
        fileUrl: isPrivate ? null : doc.fileUrl,
        secureKind: isPrivate ? 'employee-document' : null,
        secureId: isPrivate ? doc.id : null,
        source: doc.isSystemGenerated ? 'Generated by HR' : 'Uploaded',
      });
    }

    for (const doc of legalDocs) {
      items.push({
        id: doc.id,
        kind: 'LEGAL',
        title: `${doc.documentType} — ${doc.documentNumber}`,
        category: doc.category,
        issueDate: doc.issueDate?.toISOString() ?? null,
        expiryDate: doc.expiryDate.toISOString(),
        daysUntilExpiry: this.daysUntil(doc.expiryDate),
        fileUrl: null,
        secureKind: null,
        secureId: null,
        source: `Visa / legal (${doc.status})`,
      });
    }

    for (const contract of contracts) {
      items.push({
        id: contract.id,
        kind: 'CONTRACT',
        title: `Contract ${contract.contractNumber}`,
        category: contract.contractType ?? 'Contract',
        issueDate: contract.startDate?.toISOString() ?? null,
        expiryDate: contract.endDate?.toISOString() ?? null,
        daysUntilExpiry: this.daysUntil(contract.endDate),
        fileUrl: null,
        secureKind: null,
        secureId: null,
        source: `Employment contract (${contract.status})`,
      });
    }

    for (const item of payslips) {
      // Only a locked run is a real payslip; a draft is still being edited.
      if (item.payroll?.status !== 'LOCKED') continue;
      items.push({
        id: item.id,
        kind: 'PAYSLIP',
        title: `Payslip ${String(item.payroll.month).padStart(2, '0')}/${item.payroll.year}`,
        category: 'Payslip',
        issueDate: new Date(
          Date.UTC(item.payroll.year, item.payroll.month - 1, 1),
        ).toISOString(),
        expiryDate: null,
        daysUntilExpiry: null,
        fileUrl: null,
        secureKind: null,
        secureId: null,
        source: 'Payroll',
      });
    }

    // Certificates the employee earned, which live on the nomination.
    const certificates = await this.prisma.trainingNomination.findMany({
      where: { employeeId, status: 'ATTENDED', certificateUrl: { not: null } },
      include: { session: { select: { course: { select: { title: true } } } } },
    });
    for (const cert of certificates) {
      items.push({
        id: cert.id,
        kind: 'CERTIFICATE',
        title: `Certificate — ${cert.session.course.title}`,
        category: 'Training certificate',
        issueDate: cert.attendedAt?.toISOString() ?? null,
        expiryDate: cert.certificateExpiry?.toISOString() ?? null,
        daysUntilExpiry: this.daysUntil(cert.certificateExpiry),
        fileUrl: cert.certificateUrl,
        secureKind: null,
        secureId: null,
        source: 'Training',
      });
    }

    items.sort((a, b) => (b.issueDate ?? '').localeCompare(a.issueDate ?? ''));

    const expiringSoon = items.filter(
      (i) => i.daysUntilExpiry !== null && i.daysUntilExpiry >= 0 && i.daysUntilExpiry <= 90,
    );
    const expired = items.filter(
      (i) => i.daysUntilExpiry !== null && i.daysUntilExpiry < 0,
    );

    return {
      success: true,
      data: {
        items,
        summary: {
          total: items.length,
          byKind: items.reduce<Record<string, number>>((acc, i) => {
            acc[i.kind] = (acc[i.kind] ?? 0) + 1;
            return acc;
          }, {}),
          expiringSoon: expiringSoon.length,
          expired: expired.length,
        },
      },
    };
  }

  /** Resolve a private employee document for the secure-download route. */
  async fileFor(documentId: string, user: any) {
    const doc = await this.prisma.employeeDocument.findUnique({
      where: { id: documentId },
      include: { employee: { select: { id: true, branchId: true } } },
    });
    if (!doc) return null;
    assertInBranch(doc.employee.branchId);
    this.assertMayRead(doc.employeeId, user);

    const ref = doc.privateRef ?? doc.fileUrl;
    if (!StorageService.isPrivateRef(ref)) return null;

    return { ref, fileName: doc.fileName, ownerEmployeeId: doc.employeeId };
  }
}
